CREATE TABLE Feedback (
    Id SERIAL PRIMARY KEY,
    UserId VARCHAR(100) NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content VARCHAR(1000) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
